name = "jonstodle-talks"
compatibility_date = "2023-03-03"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "jgs-talks"
database_id = "55e60706-aa28-45c1-8d0e-84289240815e"
