// Generated by Xata Codegen 0.18.0. Please do not edit.
import {
  BaseClientOptions,
  buildClient,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "talks",
    columns: [
      { name: "title", type: "string", notNull: true, defaultValue: '""' },
      {
        name: "date",
        type: "datetime",
        notNull: true,
        defaultValue: "1970-01-01T00:00:00Z",
      },
      { name: "slides", type: "string" },
      { name: "video", type: "string" },
      { name: "code", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Talks = InferredTypes["talks"];
export type TalksRecord = Talks & XataRecord;

export type DatabaseSchema = {
  talks: TalksRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Jon-Grythe-St-dle-s-workspace-djd3ai.eu-west-1.xata.sh/db/jgs",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
